### ISSUE TITLE
How to use razzle-plugin-scss? 

### ISSUE THREAD

**Issue by ksuess** [RedTurtle/design-volto-theme#150]
You are using scss in your project. If try to adapt your configuration, I get the following error. Do you have a hint for me, what I am missing? 

```
TypeError: razzlePlugin is not a function
    at runPlugin (/Users/ksuess/Volto/volto-sandbox/my-volto-project/node_modules/razzle/config/runPlugin.js:29:10)
    at /Users/ksuess/Volto/volto-sandbox/my-volto-project/node_modules/razzle/config/createConfig.js:579:16
    at Array.forEach (<anonymous>)
    at module.exports (/Users/ksuess/Volto/volto-sandbox/my-volto-project/node_modules/razzle/config/createConfig.js:578:13)
    at main (/Users/ksuess/Volto/volto-sandbox/my-volto-project/node_modules/razzle/scripts/start.js:69:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
✨  Done in 4.85s.
```

I think it is expected that razzle-plugin-scss exports a *modify* function, but it does export *modifyWebpackConfig*.

**Comment by fpkpmg** [comment]
Hi,

I got this error. Upgrading to the latest version of razzle resolved the issue for me (3.1.7 -> 3.3.7)

**Comment by nzambello** [comment]
@ksuess did you resolved upgrading razzle?

**Comment by pnicolli** [comment]
Stale issue, closing. Reopen if needed.
